DROP TABLE IF EXISTS nyc_free_wifis;

CREATE TABLE nyc_free_wifis(
	object_id VARCHAR,
	boro VARCHAR,
	type VARCHAR,
	provider VARCHAR,
	setting_name VARCHAR, --location name
	setting_descrip VARCHAR,
	lat VARCHAR,
	long VARCHAR,
	X VARCHAR,
	Y VARCHAR,
	location_t VARCHAR, -- location description 
	remarks VARCHAR,
	city VARCHAR, -- place within the borough
	ssid VARCHAR,
	source_id VARCHAR, --?
	activated VARCHAR, -- have to strip time.
	boro_code VARCHAR,
	boro_name VARCHAR,
	nta_code VARCHAR,
	nta_name VARCHAR,
	coun_dist VARCHAR, -- council district number
	post_code VARCHAR,
	boro_cd VARCHAR,
	CT2010 VARCHAR, -- cencus data based on location ?
	BCTCB2010 VARCHAR, --combined value of boro_cd and census data ?
	bin VARCHAR, -- building identification number
	bbl VARCHAR, -- borough block lot
	doitt_id VARCHAR, -- idenitification number automatically generated by map
	lat_long VARCHAR -- we have lat and long as separate fields
);

\COPY nyc_free_wifis FROM 'NYC_Wi-Fi_Hotspot_Locations.csv' CSV HEADER;

DELETE FROM nyc_free_wifis 
WHERE lat is null
	or long is null
	or nta_name is null 
	or city is null
	or boro_name is null
	or provider is null
	or ssid is null
;

-------------------------------------------------------------------------------------

INSERT INTO providers (name)
SELECT DISTINCT provider
FROM nyc_free_wifis;

INSERT INTO ssids (ssid)
SELECT DISTINCT ssid
FROM nyc_free_wifis;

INSERT INTO providers_ssids (provider, ssid)
SELECT DISTINCT provider, ssid
FROM nyc_free_wifis;

INSERT INTO boroughs (name, code)
SELECT DISTINCT boro_name, boro_code::INTEGER
FROM nyc_free_wifis;

INSERT INTO cities (name, boro)
SELECT DISTINCT city, boro_name
FROM nyc_free_wifis;

INSERT INTO locations (lat, long, coun_dist, post_code, city_id)
SELECT DISTINCT n.lat::FLOAT, n.long::FLOAT, n.coun_dist::INTEGER, n.post_code,
	c.id
FROM nyc_free_wifis as n 
INNER JOIN cities AS c ON (c.name = n.city AND c.boro = n.boro_name);

INSERT INTO hotspots (id, type, remarks, activated, bin, bbl,
	setting_descrip, setting_type, provider, lat, long)	
SELECT DISTINCT object_id::INTEGER, type, remarks, to_date(activated, 'MM/DD/YYYY'),
	bin, bbl, setting_descrip, location_t, provider, lat::FLOAT, long::FLOAT
FROM nyc_free_wifis;
